### ISSUE TITLE
The blog is a tad hard to read

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs-cluster-website#25]
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/1211152/42031475-af6724ac-7ad6-11e8-88fc-d189a9108a45.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1211152/42031536-d6dc26a4-7ad6-11e8-8728-0cf31a3acd05.png">

Something like:
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/1211152/42031696-7975331a-7ad7-11e8-82ef-6e6e1d5af7f1.png">

**Comment by hsanjuan** [comment]
@diasdavid I tend to agree, do you think this affects the docs in general?

@akrych what should we do here? 

Maybe just promoting those titles to h1? Or do we rework the font properties?

**Comment by akrych** [comment]
Sure :) I will propose some small corections to text, which will improve the readability of posts.

**Comment by lanzafame** [comment]
I agree with everything except the [middle-endian date format](https://en.wikipedia.org/wiki/Endianness#Middle-endian)... 😛

**Comment by kishansagathiya** [comment]
I can benefit from darker+thicker fonts as well :smile: . Kinda like what github uses. It's little light to see for me. This will make more people finish through the docs. Or may be it's just me :smile:

**Comment by kyledrake** [comment]
@kishansagathiya No I agree, I'm going to :+1: on a font change here. The font on the site is pretty hard to read. I was about to file an issue about it.

**Comment by kishansagathiya** [comment]
@kyledrake awsome

**Comment by akrych** [comment]
@hsanjuan 

My proposition for blog/news page (I add also switch button for change to dark backgorund theme - to pepole who like read white letters on dark:)

![cluster_website_news](https://user-images.githubusercontent.com/22168118/46293548-24523880-c594-11e8-8790-52b853f1c041.png)

![cluster_website_news2](https://user-images.githubusercontent.com/22168118/46293552-274d2900-c594-11e8-9682-2644a8544e42.png)

**Comment by kyledrake** [comment]
The issue isn't really light vs dark, I really do think the font/size is
just not very readable. I would switch to a different font or something a
little stronger. It's not necessary to make a dark theme to resolve this
(but feel free!), just a change to the font.

**Comment by akrych** [comment]
@kyledrake 

> The issue isn't really light vs dark, I really do think the font/size is
just not very readable. I would switch to a different font or something a
little stronger. It's not necessary to make a dark theme to resolve this
(but feel free!), just a change to the font.

Hello :) I know Kyle, I change font here to "Inter UI" font. The light/dark version it was my additional proposition.

**Comment by meiqimichelle** [comment]
@akrych This is much improved! A few points of feedback:

- Can you look at a design that limits **line length** at desktop screen sizes to improve readability? So, we'd need one design for desktop, and another for smaller screen sizes. See more here [Readability: the Optimal Line Length](https://baymard.com/blog/line-length-readability) and here [Butterick's Practical Typography](https://practicaltypography.com/line-length.html) (<-- love that last resource, lots of fun stuff on all sorts of fine typography points).

- I think the sub-headings are still a little bit hard to distinguish. You might consider adjusting line height. Right now, the space between the paragraphs is very similar (or maybe the same?) to the space above and below the headings. Bumping up the space above the headings to give the sections a bit more breathing room might help create stronger information hierarchy on the page. (I'm not sure exactly of the best arrangement, but I'd take another look at the relationship between the paragraph line height; the space between paragraphs; the space between bullets; heading line height; etc; to make sure they're dialed in the best way they can be to make it clear what belongs to what.)

<details>
<summary>For those following along at home, expand for the gist of the line length thing, from the first linked article:</summary>

Having the right amount of characters on each line is key to the readability of your text. It shouldn’t merely be your design that dictates the width of your text, it should also be a matter of legibility.

The optimal line length for your body text is considered to be 50-60 characters per line, including spaces (“Typographie”, E. Ruder). Other sources suggest that up to 75 characters is acceptable. So what’s the downsides of violating this range?

- Too wide – if a line of text is too long the reader’s eyes will have a hard time focusing on the text. This is because the line length makes it difficult to gauge where the line starts and ends. Furthermore it can be difficult to continue onto the correct line in large blocks of text.
- Too narrow – if a line is too short the eye will have to travel back too often, breaking the reader’s rhythm. Too short lines also tend to stress readers, making them begin on the next line before finishing the current one (hence skipping potentially important words).

It turns out that the subconscious mind is energized when jumping to the next line (as long as it doesn’t happen too frequently, see above bullet point). At the beginning of every new line the reader is focused, but this focus gradually wears off over the duration of the line (“Typographie”, E. Ruder).

In order to avoid the drawbacks of too long and too short lines, but still energize your readers and keep them engaged, we suggest keeping your text within the range of 50-75 characters per line.

**Comment by akrych** [comment]
@meiqimichelle I made some corrections to the line  line length this blog. You can see and comment it here
(All > Let me know if you are not familiar with inVision and needs help): https://invis.io/A5P7NIAM3VZ

**Comment by olizilla** [comment]
We're leaning on tachyons css in our other sites and Web UI to bake in a [legible typescale](http://tachyons.io/docs/typography/scale/) and nudge us to think about [line lengths / measures](http://tachyons.io/docs/typography/measure/) too.

**Comment by meiqimichelle** [comment]
Blocked by #46 -- but that issue is `in progress` :)
